name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.2

      - name: Install dependencies
        run: cd frontend && pnpm install

      - name: Build frontend
        run: cd frontend && pnpm run build

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: download dependencies
        run: go mod download

      - name: build
        run: go build -v -o ./bin/ ./...
