name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.2

      - name: Get pnpm store directory
        id: pnpm-cache-dir
        run: |
          echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Restore cached deps
        id: pnpm-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.pnpm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-

      - name: Install dependencies
        run: cd frontend && pnpm install

      - name: Build frontend
        run: cd frontend && pnpm run build

      - uses: actions/cache@v4
        if: steps.pnpm-cache-restore.outputs.cache-hit != 'true'
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: Restore cached deps
        id: go-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-

      - name: download dependencies
        run: go mod download

      - name: build
        run: go build -v -o ./bin/ ./...

      - uses: actions/cache@v4
        if: steps.go-cache-restore.outputs.cache-hit != 'true'
        id: go-cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('./go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: isntall mdbook
        run: cargo install --git https://github.com/rust-lang/mdBook.git mdbook

      - name: build docs
        run: ./scripts/mdbook-build.sh
